# Site settings
theme: jekyll-theme-leap-day
title: YHQ's Blog                     #你博客的标题
#SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
#header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: yanghq0622@qq.com    
description: "个人学习小站 "              #网站介绍
#keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://yanghq0622.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "Welcome to my GitHub Pages"
#sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
